# Default values for apache-vector-chart.
replicaCount: 1

apache:
  image:
    repository: httpd
    tag: "2.4"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

vector:
  image:
    repository: timberio/vector
    tag: "0.34.0-alpine"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    sources:
      apache_access_logs:
        type: file
        include:
          - /var/log/apache2/access.log
        read_from: beginning
      apache_error_logs:
        type: file
        include:
          - /var/log/apache2/error.log
        read_from: beginning
    transforms:
      parse_access_logs:
        type: remap
        inputs:
          - apache_access_logs
        source: |
          . = parse_apache_log!(.message, "combined")
          .timestamp = parse_timestamp(.timestamp, "%d/%b/%Y:%H:%M:%S %z") ?? now()
          .log_type = "access"
      parse_error_logs:
        type: remap
        inputs:
          - apache_error_logs
        source: |
          . = parse_apache_log!(.message, "error")
          .log_type = "error"
    outputs:
      stdout:
        type: console
        encoding:
          codec: json

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}